// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
	return web;
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB29bwKvrfpETAWsBOuP8x1DAvztsvGE_M',
    appId: '1:801784689445:web:7c054236d5470ead85a0cc',
    messagingSenderId: '801784689445',
    projectId: 'shanmukha-app',
    authDomain: 'shanmukha-app.firebaseapp.com',
    storageBucket: 'shanmukha-app.firebasestorage.app',
    measurementId: 'G-WLBYHHTQQZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6kEf5aulibdZU9s-A_7A6aSx_zXJEUmg',
    appId: '1:801784689445:android:8142feaa9f35c6d385a0cc',
    messagingSenderId: '801784689445',
    projectId: 'shanmukha-app',
    storageBucket: 'shanmukha-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJi6m_6Egxq9JgfrZJpMExDQx_ETlqToA',
    appId: '1:801784689445:ios:0cd9603e0a1b6e1585a0cc',
    messagingSenderId: '801784689445',
    projectId: 'shanmukha-app',
    storageBucket: 'shanmukha-app.firebasestorage.app',
    iosClientId: '801784689445-0f54hsd3nh928fq9ugob60f81jcf7u6v.apps.googleusercontent.com',
    iosBundleId: 'com.example.tempProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJi6m_6Egxq9JgfrZJpMExDQx_ETlqToA',
    appId: '1:801784689445:ios:0cd9603e0a1b6e1585a0cc',
    messagingSenderId: '801784689445',
    projectId: 'shanmukha-app',
    storageBucket: 'shanmukha-app.firebasestorage.app',
    iosClientId: '801784689445-0f54hsd3nh928fq9ugob60f81jcf7u6v.apps.googleusercontent.com',
    iosBundleId: 'com.example.tempProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB29bwKvrfpETAWsBOuP8x1DAvztsvGE_M',
    appId: '1:801784689445:web:e0bfb22ff006a93d85a0cc',
    messagingSenderId: '801784689445',
    projectId: 'shanmukha-app',
    authDomain: 'shanmukha-app.firebaseapp.com',
    storageBucket: 'shanmukha-app.firebasestorage.app',
    measurementId: 'G-GBHZWFVWKS',
  );
}
